CREATE TABLE TJ_TTYYXXB
(

ID	int IDENTITY(1,1) PRIMARY KEY not null,
YYR	Nvarchar(10) NOT NULL,
YYTT	Nvarchar(20) NOT NULL,
YYSJ	Datetime NOT NULL,
THRS	Int NOT NULL,
LXR	Nvarchar(10) NOT NULL, 
LXDH	Nvarchar(20) NOT NULL,
CZYBM	Nvarchar(10) NOT NULL,
TJSJ	Datetime



)